name: CI
on:
  push:
    branches:
      - main

jobs:
  test:

    name: 'Tests & Linting'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .
